# Using Torch and Numpy

In [1]:
import torch
import numpy as np

#### Converting numpy array to tensor

In [12]:
x = np.array([[1.0,2,3], [6,5,4]])
x

array([[1., 2., 3.],
       [6., 5., 4.]])

Passing a variable to `torch.from_numpy()`

In [13]:
y = torch.from_numpy(x)
y

tensor([[1., 2., 3.],
        [6., 5., 4.]], dtype=torch.float64)

In [14]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

#### Converting tensor to numpy array

Using the `.numpy()` property

In [15]:
z = y.numpy()
z

array([[1., 2., 3.],
       [6., 5., 4.]])