# Linear Regression

This section builds a linear regression model which will predict crop yeilds in hte region by looking at average temp, rainfall and humidity.

In [2]:
import torch
import numpy as np

In [10]:
# Input values of temp, rainfall, humidity in a numpy array
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [11]:
# Target  value of crop yield, apples,oranges.
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [12]:
#Converting inputs and targets to tensors
tensor_inputs = torch.from_numpy(inputs)
tensor_targets = torch.from_numpy(targets)
print(tensor_inputs,tensor_targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Linear regression model from scratch

Defining weights and biases

In [13]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

The model simply performs matrix multiplication. 

Note `@ operator` represents matrix multiplication in pytorch. and a `.t` represents transpose of a matrix.

In [14]:
def model(x):
    return x @ w.t() + b

### Perdications Using the model

In [16]:
predictions = model(tensor_inputs)
print(predictions)

tensor([[ 50.7197, -11.8145],
        [ 57.0893, -25.6647],
        [ 78.5908,  36.1860],
        [ 67.1980, -37.7570],
        [ 39.0483, -19.6343]], grad_fn=<AddBackward0>)


Comparing the predictions with actual target.

In [17]:
print(tensor_targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Difference is calculated between `predictions` and `targets`. The `.numel()` method gives number of elements in a tensor, and `.sum()` method gives the sum of elements in a tensor. Here the mean squared error (MSE) is being calculated.

In [20]:
diff = predictions - tensor_targets
torch.sum(diff * diff)/ diff.numel()

tensor(6528.3765, grad_fn=<DivBackward0>)

# Loss Function

Loss function is used to evaluate how well the model is perofrming. In this case we will use MSE loss.

In [22]:
def mse(t1,t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()